import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const appPath = path.resolve('sau_frontend/src/App.vue')
const routerPath = path.resolve('sau_frontend/src/router/index.js')
const viewPath = path.resolve('sau_frontend/src/views/AIPublish.vue')

const appSource = fs.readFileSync(appPath, 'utf8')
const routerSource = fs.readFileSync(routerPath, 'utf8')
const viewExists = fs.existsSync(viewPath)
const viewSource = viewExists ? fs.readFileSync(viewPath, 'utf8') : ''

test('app shell exposes ai publish navigation between task progress and about', () => {
  assert.equal(appSource.includes('index="/ai-publish"'), true)

  const taskProgressIndex = appSource.indexOf('index="/task-progress"')
  const aiPublishIndex = appSource.indexOf('index="/ai-publish"')
  const aboutIndex = appSource.indexOf('index="/about"')

  assert.equal(taskProgressIndex >= 0, true)
  assert.equal(aiPublishIndex > taskProgressIndex, true)
  assert.equal(aboutIndex > aiPublishIndex, true)
})

test('router registers ai publish view route', () => {
  assert.equal(routerSource.includes("import AIPublish from '../views/AIPublish.vue'"), true)
  assert.equal(routerSource.includes("path: '/ai-publish'"), true)
  assert.equal(routerSource.includes("name: 'AIPublish'"), true)
  assert.equal(routerSource.includes('component: AIPublish'), true)
})

test('ai publish page keeps chat behaviors while exposing the light-reskin structure', () => {
  assert.equal(viewExists, true)
  assert.equal(viewSource.includes('class="ai-publish-page"'), true)
  assert.equal(viewSource.includes('class="ai-session-sidebar"'), true)
  assert.equal(viewSource.includes('class="ai-chat-stage"'), true)
  assert.equal(viewSource.includes('class="ai-message-list"'), true)
  assert.equal(viewSource.includes('class="ai-composer"'), true)
  assert.equal(viewSource.includes("import { aiPublishApi } from '@/api/aiPublish'"), true)
  assert.equal(viewSource.includes('formatConversationListTitle'), true)
  assert.equal(viewSource.includes('slice(0, 8)'), true)
  assert.equal(viewSource.includes('loadAiPublishConfig'), true)
  assert.equal(viewSource.includes('aiPublishApi.uploadAttachment'), true)
  assert.equal(viewSource.includes('startAiChat'), true)
  assert.equal(viewSource.includes('new EventSource(aiPublishApi.getChatTaskStreamUrl(taskId))'), true)
  assert.equal(viewSource.includes('pendingAttachments'), true)
  assert.equal(viewSource.includes('handleAttachmentSelection'), true)
  assert.equal(viewSource.includes('removePendingAttachment'), true)
  assert.equal(viewSource.includes('attachments:'), true)
  assert.equal(viewSource.includes('lastUserMessageId'), true)
  assert.equal(viewSource.includes("eventSource.addEventListener('assistant-finished'"), true)
  assert.equal(viewSource.includes('accept="image/*,audio/*,video/*"'), true)
  assert.equal(viewSource.includes('attachment.category'), true)
  assert.equal(viewSource.includes('class="ai-message-attachments"'), true)
  assert.equal(viewSource.includes('class="ai-message-attachment-chip"'), true)
  assert.equal(viewSource.includes('formatMessageAttachmentLabel'), true)
  assert.equal(viewSource.includes('class="ai-task-preview-popover"'), true)
  assert.equal(viewSource.includes('confirmTaskPreview'), true)
  assert.equal(viewSource.includes('createAiConversation'), true)
  assert.equal(viewSource.includes('deleteAiConversation'), true)
  assert.equal(viewSource.includes('@click.stop="deleteAiConversation(conversation.id)"'), true)
  assert.equal(viewSource.includes('sendAiMessage'), true)
  assert.equal(viewSource.includes('activeConversationId'), true)
  assert.equal(viewSource.includes('AI_PUBLISH_STORAGE_KEY'), true)
  assert.equal(viewSource.includes('window.localStorage.getItem'), true)
  assert.equal(viewSource.includes('window.localStorage.setItem'), true)
  assert.equal(viewSource.includes('repairPossibleMojibake'), true)
  assert.equal(viewSource.includes("new TextDecoder('utf-8', { fatal: true })"), true)
  assert.equal(viewSource.includes('repairStoredConversation'), true)
  assert.equal(viewSource.includes('repairTaskPreview'), true)
  assert.equal(viewSource.includes('visibleConversationMessages'), true)
  assert.equal(viewSource.includes('先到关于页接入 API'), true)

  assert.equal(viewSource.includes('class="ai-chat-surface"'), true)
  assert.equal(viewSource.includes('ai-session-card-subtle'), true)
  assert.equal(viewSource.includes('class="ai-empty-orb"'), true)
  assert.equal(viewSource.includes('ai-orb-avatar'), true)
  assert.equal(viewSource.includes('class="ai-composer-float"'), true)
  assert.equal(viewSource.includes('class="ai-composer-send-orb"'), true)
  assert.equal(viewSource.includes('class="ai-task-preview-sheet"'), true)
  assert.equal(viewSource.includes('class="ai-sidebar-label"'), false)
  assert.equal(viewSource.includes('class="ai-chat-kicker"'), false)
  assert.equal(viewSource.includes('class="ai-chat-subtitle"'), false)
  assert.equal(viewSource.includes('class="ai-suggestion-grid"'), false)

  assert.equal(viewSource.includes('class="ai-chat-header-actions"'), false)
  assert.equal(viewSource.includes('v-model="aiConfigDialogVisible"'), false)
  assert.equal(viewSource.includes('class="ai-config-dialog"'), false)
  assert.equal(viewSource.includes('class="ai-model-select"'), false)
  assert.equal(viewSource.includes('v-model="selectedModel"'), false)
  assert.equal(viewSource.includes('saveAiPublishConfig'), false)
  assert.equal(viewSource.includes('testAiPublishConfig'), false)
})
